import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider 
      appearance = {{
        
        variables:{
          colorText:'#3d4005',
          colorBackground:"#edf55b",
          colorPrimary:"#1ad9a3",
          colorInputBackground:"#eaf2b6",
          colorInputText:'#3d4005'
        }
      }}>
      <body className={`${inter.className} bg-dark-2`}>{children}</body>
      </ClerkProvider>
      
    </html>
  );
}
